# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/Paris"
    groups:
      actions:
        patterns:
          - "*"
    reviewers:
      - "frgfm"
    assignees:
      - "frgfm"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    reviewers:
      - "frgfm"
    assignees:
      - "frgfm"
    groups:
      build:
        patterns:
          - "uv-build"
      quality:
        patterns:
          - "prek"
          - "ruff"
          - "ty"
      test:
        patterns:
          - "pytest"
          - "pytest-cov"
          - "pytest-pretty"
      docs:
        patterns:
          - "mkdocs"
          - "mkdocs-material"
          - "mkdocstrings"
    allow:
      - dependency-name: "uv-build"
      - dependency-name: "prek"
      - dependency-name: "ruff"
      - dependency-name: "ty"
      - dependency-name: "pytest"
      - dependency-name: "pytest-cov"
      - dependency-name: "pytest-pretty"
      - dependency-name: "mkdocs"
      - dependency-name: "mkdocs-material"
      - dependency-name: "mkdocstrings"
