default_language_version:
    python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: ^docs/mkdocs\.yml$
      - id: debug-statements
        language_version: python3
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'main']
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: make ruff-lint-fix
        language: system
        pass_filenames: false
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ruff-format
        name: ruff format
        entry: make ruff-format-fix
        language: system
        pass_filenames: false
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ty
        name: ty check
        entry: make typing-check
        language: system
        pass_filenames: false
