blank_issues_enabled: true
contact_links:
  - name: Usage questions
    url: https://github.com/frgfm/torch-scan/discussions
    about: Ask questions and discuss with other TorchCAM community members
