name: docs
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  UV_TORCH_BACKEND: cpu

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
          architecture: x64
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          activate-environment: true
      - name: Install dependencies
        run: make install-docs
      - name: Build documentation
        run: make build-docs
      - name: Documentation sanity check
        run: |
          test -e docs/site/index.html
          test -e docs/site/installing.html
          test -e docs/site/model-support.html
          test -e docs/site/metrics.html
          test -e docs/site/torchscan.html
          test -e docs/site/modules.html
          test -e docs/site/process.html
          test -e docs/site/utils.html
          test -e docs/site/changelog.html
          test -e docs/site/latest/changelog.html
      - name: Install SSH Client 🔑
        if: github.event_name == 'push'
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Deploy to Github Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          BRANCH: gh-pages
          FOLDER: docs/site
          COMMIT_MESSAGE: "[skip ci] Documentation updates"
          CLEAN: true
          SSH: true
