# This is a basic workflow to help you get started with Actions

name: Package build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pkg-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

  pkg-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r .circleci/requirements.txt
          coverage run -m unittest discover test/
          coverage xml
          python-codacy-coverage -r coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage.xml # optional
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)

  flake8-py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Run flake8
        run: |
          pip install flake8
          flake8 --version
          flake8 ./

  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r docs/requirements.txt
          sphinx-build docs/source docs/build -a
