name: page-build

on:
  page_build

jobs:
  check-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
          architecture: x64
      - name: Check status
        run: |
          import os
          status, errormsg = os.getenv("STATUS"), os.getenv("ERROR")
          if status != "built":
              raise AssertionError(
                  f"There was an error building the page on GitHub Pages.\n\n"
                  f"Status: {status}\n\nError message: {errormsg}"
              )
        shell: python
        env:
          STATUS: ${{ github.event.build.status }}
          ERROR: ${{ github.event.build.error.message }}
